# code: language=Ansible insertSpaces=true tabSize=2


- name: Install unattended-upgrades
  package:
    name: unattended-upgrades
    state: present
  tags: [never, setup]

- name: Configure unattended-upgrades
  template:
    src: "51unattended-upgrades-ansible.j2"
    dest: "{{ jpclipffel_system_autoupdate_unattended_upgrades_file }}"
    mode: 0644
  tags: [never, setup]

- name: Configure auto-upgrades
  template:
    src: "21auto-upgrades-ansible.j2"
    dest: "{{ jpclipffel_system_autoupdate_auto_upgrades_file }}"
    mode: 0644
  tags: [never, setup]

# ---

- name: Remove unattended-upgrades configuration
  file:
    path: "{{ jpclipffel_system_autoupdate_unattended_upgrades_file }}"
    state: absent
  tags: [never, teardown, remove]

- name: Remove auto-upgrades configuration
  file:
    path: "{{ jpclipffel_system_autoupdate_auto_upgrades_file }}"
    state: absent
  tags: [never, teardown, remove]

- name: Remove unattended-upgrades
  package:
    name: "unattended-upgrades"
    state: absent
  tags: [never, remove]
