# code: language=Ansible insertSpaces=true tabSize=2


- name: Lock Ansible user account password
  user:
    name: "{{ jpclipffel_system_ansible_user_name }}"
    state: present
    password_lock: true
  when:
    - jpclipffel_system_ansible_user_pwdlock is true
    - jpclipffel_system_ansible_public_keys_files | length > 2
      or jpclipffel_system_ansible_public_keys | length > 2
      or jpclipffel_system_ansible_public_keys_git | length > 2
  tags: [never, setup]

# ---

- name: Unlock Ansible user account password
  user:
    name: "{{ jpclipffel_system_ansible_user_name }}"
    state: present
    password_lock: false
  tags: [never, teardown, remove]
