# code: language=Ansible insertSpaces=true tabSize=2


- name: Set custom facts
  set_fact:
    jpclipffel_system_ansible_pip: "python{{ ansible_python.version.major }}-pip"
  tags: [always]

- name: Setup Ansible user account
  user:
    name: "{{ jpclipffel_system_ansible_user_name }}"
    comment: "{{ jpclipffel_system_ansible_user_comment }}"
    state: present
  tags: [never, setup]

- name: Update packages list
  apt:
    update_cache: true
  tags: [never, setup]

- include_tasks:
    file: "{{ item }}"
  loop:
    - services/ssh.yml
    - services/sudo.yml
    - services/pip.yml
    - services/password.yml
  tags: [always]
