# SSH server package name
jpclipffel_system_sshd_package: "openssh-server"

# SSH server service name
jpclipffel_system_sshd_service: "sshd"

# SSH server cofiguration root path
jpclipffel_system_sshd_config_root: "/etc/ssh/sshd_config.d"

# SSH server configuration file
jpclipffel_system_sshd_config_file: "{{ jpclipffel_system_sshd_config_root }}/ansible_sshd_config"

# SSH server listening ports
jpclipffel_system_sshd_ports:
  - 22

# SSH server host keys list (identifies the server, not the client).
# If empty, the default host keys are used.
#
# Fields:
# 'path': Key file path on the Ansible controller
# 'name': Key file name on the target host
#
# Example value:
# jpclipffel_system_sshd_host_keys_files:
#   - path: "{{ ansible_host_rsa_key }}"
#     name: "ssh_host_rsa_key"
#
jpclipffel_system_sshd_host_keys_files: []
